spring:
  redis:
    port: ${redis.port}
    password: ${redis.password}
    host: ${redis.host}
    database: ${redis.database}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
      shutdown-timeout: 100ms